version: '2.2'
services:
  redis_master:
    image: redis:3
    container_name: redis_master
    ports:
      - '6379:6379'
  redis_slave:
    image: redis:3
    container_name: redis_slave
    command: redis-server --port 6380 --slaveof "${EXTERNAL_HOST}" 6379 --slave-announce-ip "${EXTERNAL_HOST}"
    ports:
      - '6380:6380'
  sentinel:
    build: ./sentinel
    container_name: redis_sentinel
    ports:
      - '26379:26379'
    environment:
      - SENTINEL_NAME=mysentinel
      - HOST_IP="${EXTERNAL_HOST}"
